### ISSUE TITLE
lilith 8.0.0 does not allow to connect log4j2 socket appender

### ISSUE THREAD

**Issue by taorg** [huxi/lilith#21]
It seems new security feature introduced with lilith 8.0.0  blocks socket appender connections from Log4j2 socket appender.

The  "Unauthorized deserialization attempt! {}"  message is produced.
These two classes are missed:
whitelist.add("java.util.Collections$EmptyMap"); 
whitelist.add("org.apache.logging.log4j.ThreadContext$EmptyThreadContextStack");

**Comment by taorg** [comment]
Well, with a more complete test I've found 2 more classes:
whitelist.add("org.apache.logging.log4j.message.ParameterizedMessage");
whitelist.add("org.apache.logging.log4j.message.ObjectMessage");

**Comment by huxi** [comment]
Sorry about that. It's a bit trial and error regarding the allowed classes, unfortunately. I thought I caught all of them with my sandbox.
Don't hesitate to reopen this bug if you find any other missing classes.

**Comment by SagaciousZed** [comment]
I can't reopen this but, classes for Markers in log4j2 seem to be missing from the whitelist.

I've tried adding the following to the whitelist  ```java
whitelist.add("org.apache.logging.log4j.Marker");
whitelist.add("org.apache.logging.log4j.MarkerManager");
whitelist.add("org.apache.logging.log4j.MarkerManager$Log4jMarker");
```

However, I still get the following exception and unable to fix this with a whitelist entry```
WARN  - Unauthorized deserialization attempt! [Lorg.apache.logging.log4j.Marker;
WARN  - Exception (java.lang.ClassNotFoundException: 'Unauthorized deserialization attempt! [Lorg.apache.logging.log4j.Marker;') while reading events. Adding eventWrapper with empty event and stopping...
java.lang.ClassNotFoundException: Unauthorized deserialization attempt! [Lorg.apache.logging.log4j.Marker;
	at de.huxhorn.lilith.engine.impl.eventproducer.WhitelistObjectInputStream.resolveClass(WhitelistObjectInputStream.java:116) ~[de.huxhorn.lilith.engine-8.0.1-SNAPSHOT.jar:na]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1664) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_66]
	at de.huxhorn.lilith.engine.impl.eventproducer.AbstractStreamEventProducer$ReceiverRunnable.run(AbstractStreamEventProducer.java:139) ~[de.huxhorn.lilith.engine-8.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]```

**Comment by huxi** [comment]
I likely fixed your specific `Marker` problem in 3c27569362f9fe8c but I found some much bigger problems in log4j itself in the process.

Opened [LOG4J2-1226 - Message instances are simply serialized. They mustn't.](https://issues.apache.org/jira/browse/LOG4J2-1226) over at the log4j2 project. I'll reopen this bug to keep it in mind.

**Comment by SagaciousZed** [comment]
I can confirm that 3c27569 fixed it and works with how I am using markers in Log4j2. Thanks!

**Comment by huxi** [comment]
Thanks for the feedback!

**Comment by tbaronetti** [comment]
Hi Jörn,

I really like Lilith and want to use it for all my application logging. 

I am having a similar problem to that described by taorg. I am connecting to Lilith via ch.qos.logback.classic.net.SocketAppender on localhost port 4560 from a simple java HelloWorld example. I receive the message:

Exception (java.lang.ClassNotFoundException: 'Unauthorized deserialization attempt! java.util.Collections$EmptyMap') while reading events. Adding eventWrapper with empty event and stopping...  

I see you have already fixed a bug in relation to this. Do I need to change something?

Tim

**Comment by huxi** [comment]
Hi Tim.

The fix isn't released yet. You could build Lilith yourself in the meantime. I'll try to release a new version this weekend. Sorry about this.
I hoped to get [Message instances are simply serialized. They mustn't.](https://issues.apache.org/jira/browse/LOG4J2-1226) fixed before a release but they aren't moving. :(

Cheers,
Jörn.

**Comment by tbaronetti** [comment]
Thanks very much for your quick response, Jörn. I look forward to receiving the update when available. In the meantime I will try to add a whitelist entry in the source code and build it.

**Comment by huxi** [comment]
You don't have to change the source. It's already fixed in the master branch. Just build as described in the readme, i.e. first sulky, then lilith.

**Comment by tbaronetti** [comment]
Hi Jörn,

Rebuilding from source worked fine. Thanks very much for your help. I will experiment further with all the different appender types. Excellent. :-)

Tim

**Comment by taorg** [comment]
Hello again Jörn,
I'm testing an application with log4j2 2.6.2 and lilith 8.1.0 build today.
I've got several errors like this within lilith logging:
  Unauthorized deserialization attempt! [I
  Level
  WARN
  Logger
  de.huxhorn.lilith.engine.impl.eventproducer.WhitelistObjectInputStream
I think, trying to serialize an array
And it also breaks connection between log4j2 client, I got this from terminal
2016-07-12 16:53:20,601 qtp1611373863-14 ERROR Unable to write to stream TCP:127.0.0.1:4445 for appender socket: org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to TCP:127.0.0.1:4445
2016-07-12 16:53:20,602 qtp1611373863-14 ERROR An exception occurred processing Appender socket org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to TCP:127.0.0.1:4445
        at org.apache.logging.log4j.core.net.TcpSocketManager.write(TcpSocketManager.java:144)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:156)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.writeByteArrayToManager(AbstractOutputStreamAppender.java:129)
        at org.apache.logging.log4j.core.appender.SocketAppender.directEncodeEvent(SocketAppender.java:252)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:113)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:104)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:155)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:128)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:119)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:375)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:359)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:381)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:376)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:359)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:349)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2005)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1876)
        at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:437) 
.......
.......
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at org.apache.logging.log4j.core.net.TcpSocketManager.write(TcpSocketManager.java:132)
        ... 109 more

If you need more info just tell me.
Greetings

**Comment by huxi** [comment]
Why did you close this? Did you find the culprit yourself?

**Comment by taorg** [comment]
Hello huxi,
Sorry I was a few days out.
No, I haven't yet.
I'll do it today, I'll tell you what I see.
