### ISSUE TITLE
Unable to build lilith

### ISSUE THREAD

**Issue by jlanzarotta** [huxi/lilith#25]
Hi again,

When attempting to build liilith, I get the following build exception.

```
:lilith-data-eventsource-xml:testClasses
:lilith-data-eventsource-xml:test
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
                                                         :lilith-data-eventsource-xml:check
:lilith-data-eventsource-xml:build
:lilith-data-logging:javadocJar
:lilith-data-logging:sourceJar
:lilith-data-logging:signArchives SKIPPED
:lilith-data-logging:assemble
:lilith-data-logging:compileTestJava UP-TO-DATE
:lilith-data-logging:compileTestGroovy
:lilith-data-logging:processTestResources
:lilith-data-logging:testClasses
:lilith-data-logging:test

de.huxhorn.lilith.data.logging.ThrowableInfoSpec > validate toString[2] FAILED
    org.spockframework.runtime.SpockComparisonFailure at ThrowableInfoSpec.groovy:313
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

151 tests completed, 1 failed
:lilith-data-logging:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lilith-data-logging:test'.
> There were failing tests. See the report at: file:///C:/Develop/Lilith/lilith/lilith-data/logging/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 24.452 secs
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

C:\Develop\Lilith\lilith (master)
```
If I look in the report index.html file, I get:

```
Condition not satisfied:

str == expectedValue
|   |  |
|   |  java.lang.RuntimeException: Hi.
|   |  	at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:49)
|   |  	at de.huxhorn.lilith.sandbox.Log4jSandbox.main(Log4jSandbox.java:86)
|   |  Caused by: java.lang.RuntimeException: Hi Cause.
|   |  	at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:60)
|   |  	at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:45)
|   |  	... 1 more
|   |  	Suppressed: java.lang.RuntimeException
|   |  		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:61)
|   |  		... 2 more
|   |  	Suppressed: java.lang.RuntimeException: Single line
|   |  		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:62)
|   |  		... 2 more
|   |  	Suppressed: java.lang.RuntimeException: With cause and suppressed
|   |  		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:63)
|   |  		... 2 more
|   |  		Suppressed: java.lang.RuntimeException: Inner Suppressed
|   |  			at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:64)
|   |  			... 2 more
|   |  		Suppressed: java.lang.RuntimeException: Inner Suppressed with Cause
|   |  			at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:65)
|   |  			... 2 more
|   |  		Caused by: java.lang.RuntimeException: Inner Cause
|   |  			... 3 more
|   |  	Caused by: java.lang.RuntimeException: Cause
|   |  		... 3 more
|   |  	Suppressed: java.lang.RuntimeException: Multi
|   |  line
|   |  		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:67)
|   |  		... 2 more
|   false
|   1 difference (99% similarity)
|   java.lang.RuntimeException: Hi.\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:49)\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox.main(Log4jSandbox.java:86)\r\nCaused by: java.lang.RuntimeException: Hi Cause.\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:60)\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:45)\r\n\t... 1 more\r\n\tSuppressed: java.lang.RuntimeException\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:61)\r\n\t\t... 2 more\r\n\tSuppressed: java.lang.RuntimeException: Single line\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:62)\r\n\t\t... 2 more\r\n\tSuppressed: java.lang.RuntimeException: With cause and suppressed\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:63)\r\n\t\t... 2 more\r\n\t\tSuppressed: java.lang.RuntimeException: Inner Suppressed\r\n\t\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:64)\r\n\t\t\t... 2 more\r\n\t\tSuppressed: java.lang.RuntimeException: Inner Suppressed with Cause\r\n\t\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:65)\r\n\t\t\t... 2 more\r\n\t\tCaused by: java.lang.RuntimeException: Inner Cause\r\n\t\t\t... 3 more\r\n\tCaused by: java.lang.RuntimeException: Cause\r\n\t\t... 3 more\r\n\tSuppressed: java.lang.RuntimeException: Multi(-~)\nline\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:67)\r\n\t\t... 2 more\r\n
|   java.lang.RuntimeException: Hi.\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:49)\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox.main(Log4jSandbox.java:86)\r\nCaused by: java.lang.RuntimeException: Hi Cause.\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:60)\r\n\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:45)\r\n\t... 1 more\r\n\tSuppressed: java.lang.RuntimeException\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:61)\r\n\t\t... 2 more\r\n\tSuppressed: java.lang.RuntimeException: Single line\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:62)\r\n\t\t... 2 more\r\n\tSuppressed: java.lang.RuntimeException: With cause and suppressed\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:63)\r\n\t\t... 2 more\r\n\t\tSuppressed: java.lang.RuntimeException: Inner Suppressed\r\n\t\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:64)\r\n\t\t\t... 2 more\r\n\t\tSuppressed: java.lang.RuntimeException: Inner Suppressed with Cause\r\n\t\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:65)\r\n\t\t\t... 2 more\r\n\t\tCaused by: java.lang.RuntimeException: Inner Cause\r\n\t\t\t... 3 more\r\n\tCaused by: java.lang.RuntimeException: Cause\r\n\t\t... 3 more\r\n\tSuppressed: java.lang.RuntimeException: Multi(\r)\nline\r\n\t\tat de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:67)\r\n\t\t... 2 more\r\n
java.lang.RuntimeException: Hi.
	at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:49)
	at de.huxhorn.lilith.sandbox.Log4jSandbox.main(Log4jSandbox.java:86)
Caused by: java.lang.RuntimeException: Hi Cause.
	at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:60)
	at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.execute(Log4jSandbox.java:45)
	... 1 more
	Suppressed: java.lang.RuntimeException
		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:61)
		... 2 more
	Suppressed: java.lang.RuntimeException: Single line
		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:62)
		... 2 more
	Suppressed: java.lang.RuntimeException: With cause and suppressed
		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:63)
		... 2 more
		Suppressed: java.lang.RuntimeException: Inner Suppressed
			at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:64)
			... 2 more
		Suppressed: java.lang.RuntimeException: Inner Suppressed with Cause
			at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:65)
			... 2 more
		Caused by: java.lang.RuntimeException: Inner Cause
			... 3 more
	Caused by: java.lang.RuntimeException: Cause
		... 3 more
	Suppressed: java.lang.RuntimeException: Multi
line
		at de.huxhorn.lilith.sandbox.Log4jSandbox$InnerClass.foobar(Log4jSandbox.java:67)
		... 2 more

	at de.huxhorn.lilith.data.logging.ThrowableInfoSpec.validate toString(ThrowableInfoSpec.groovy:313)
```

**Comment by huxi** [comment]
Should work now. Thanks for the feedback!

**Comment by jlanzarotta** [comment]
Fantastic.  That worked... Many thanks and keep up the good work on a great tool.

**Comment by huxi** [comment]
Alright then, have fun with Lilith.
